### ISSUE TITLE
Add memory and address sanitizer

### ISSUE THREAD

**Issue by coder3101** [BoostGSoC20/ublas#11]
Address and memory sanitizers can catch many runtime memory and address violation in the code. Both GCC and Clang offers sanitizers that can be enabled with `-fsantitize=<name>` with compile and linker flag.

The sanitizers are `memory` and `address` are mutually exclusive, only one of the two can be enabled. It is due to this reason that I have decided to run memory sanitizer on Clang and address sanitizer on GCC. Since sanitizers of both of these platforms are equally effective at spotting the error, we are can be sure that things are being checked correctly on each of the toolset.

**Comment by coder3101** [comment]
Memory sanitizer is still not supported by GCC and even though, the clang supports it. The build engine (B2) does not provide support for this sanitizer. See [this sanitizer feature file](https://github.com/boostorg/build/blob/develop/src/tools/features/sanitizers-feature.jam)

However, there is a sanitizer called leak, which can be used to which also reports memory leaks and errors. I am enabling and using that sanitizer instead of memory sanitizer.

It is still possible to enable memory sanitizer but doing so requires changing Jam files and adding conditions on toolset for compilation as only Linux Clang supports this sanitizer and not Apple clang. We should instead wait for Boost.B2 to add the support for this sanitizer.


Here are the sanitization checks that are being performed.

- GCC: All version running address and undefined sanitizer.
- Clang: All version running Leak sanitizer.

uBLAS test is not being checked by sanitizers. Because [Address sanitizer is reporting some issues](https://github.com/BoostGSoC20/ublas/runs/745542707?check_suite_focus=true) with the uBLAS tests.

**Comment by coder3101** [comment]
Sanitizers have some runtime overhead, as a result, the unit test run times have spiked 2 times for GCC (which runs address sanitizer). I am marking this as done because the sanitizers are up and running on Linux and good news that Tensor test and examples report no address, undefined behaviour and memory or leak issues!

For your reference here are the files that have been affected to add the sanitizers:
- [GCC ( Address and Undefined Sanitizer )](https://github.com/BoostGSoC20/ublas/blob/88579b04c586c8df97b362182a65da297b199e78/.github/workflows/linux_gcc.yml#L122)
- [Clang (Memory leak sanitizer)](https://github.com/BoostGSoC20/ublas/blob/88579b04c586c8df97b362182a65da297b199e78/.github/workflows/linux_clang.yml#L94)

The CI will fail if any sanitizer reports some issues.

**Comment by bassoy** [comment]
> Memory sanitizer is still not supported by GCC and even though, the clang supports it. The build engine (B2) does not provide support for this sanitizer. See [this sanitizer feature file](https://github.com/boostorg/build/blob/develop/src/tools/features/sanitizers-feature.jam)

In [boost.build/examples](https://boostorg.github.io/build/manual/develop/index.html#bbv2.overview.invocation.examples) you can specify `cxxflags`. 

Would it be possible to do something like 
`b2 toolset=clang cxxflags="-g -O2 -fsanitize=address -fno-omit-frame-pointer"`
instead of using the boost.build leak sanitizer?

**Comment by coder3101** [comment]
> Would it be possible to do something like 
> `b2 toolset=clang cxxflags="-g -O2 -fsanitize=address -fno-omit-frame-pointer"`
> instead of using the boost.build leak sanitizer?

Yes, I tried but macOS apple clang does not have memory sanitizers. So it would be great if you could tell me how to add flag only on Linux and clang? I tried to look but couldn't find any examples in b2 docs for this.

**Comment by bassoy** [comment]
Generating for Linux Clang I would go with
`$BOOST_ROOT/b2 -j 4 test/tensor toolset=clang cxxstd=17 cxxflags="-g -O2 -fsanitize=address -fno-omit-frame-pointer"`

**Comment by coder3101** [comment]
> Would it be possible to do something like 
> `b2 toolset=clang cxxflags="-g -O2 -fsanitize=address -fno-omit-frame-pointer"`
> instead of using the boost.build leak sanitizer?

Okay, I got it now. I will update the CI build scripts. Here is what I have chosen: 

- Memory Sanitizer on Clang 
- Address and Undefined sanitizers on GCC.

Address and Memory Sanitizer both can't be enabled simultaneously.

**Comment by coder3101** [comment]
Yes I got that I can pass those flags on command line from b2 

Initially I was thinking of modifying the Jamfile. I will do this tomorrow, it is possible.

**Comment by coder3101** [comment]
I have added the memory sanitizer but here is a problem.

Not uBLAS.tensor but Boost. Test framework has an issue of memory-sanitizer `use of uninitialized` value. I am not sure if it is really a true issue or false positive of MEMSAN. See [this error report](https://github.com/BoostGSoC20/ublas/runs/769628767?check_suite_focus=true#step:9:228) from Memory Sanitizer. However, I see many Stackoverflow questions that mention false positives for MEMSAN. Even its wiki says some things to do before using MEMSAN.

> If you want MemorySanitizer to work properly and not produce any false positives, you must ensure that all the code in your program and in libraries it uses is instrumented (i.e. built with -fsanitize=memory). In particular, you would need to link against MSan-instrumented C++ standard library. We recommend using libc++ for that purpose.
> See https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo

I even tried using `libc++` and linked a demo code to it with sanitizer enabled and got `uninitialized use of memory` error for `std::cout<<"Hello world"`. See this:

![image](https://user-images.githubusercontent.com/22212259/84589678-da83b180-ae4d-11ea-8a8f-a28ef47c159d.png)

The current CI is failing for `Linux Clang` due to the above sanitizer reported error in Boost.Test

**Comment by bassoy** [comment]
Okay. Then postpone the utilization of the memory sanitizer and mark it as future work.
Please continue with the thread and address sanitizer which are more important - especially the adress sanitizer.
I think that you need to compile the boost.test library with corresponding flags in that case.

**Comment by coder3101** [comment]
> Then postpone the utilization of the memory sanitizer and mark it as future work

Okay, I will open an Issue here for Future works.

> Please continue with the thread and address sanitizer which is more important - especially the address sanitizer.

I already have added ADDSAN and UBSAN (Undefine SAN) to GCC and I have added THREADSAN to clang. Please note that THREADSAN slows the execution time of binaries by 5x-15x. This cannot be improved even with caching because, CACHE only caches artefacts, the delay in actual reality is being caused by longer running test times.

**Comment by bassoy** [comment]
> Please note that THREADSAN slows the execution time of binaries by 5x-15x.

Thanks for the info. We shall than disable the thread sanitizer for push and pull request for now.

**Comment by coder3101** [comment]
> Thanks for the info. We shall than disable the thread sanitizer for push and pull request for now.

I have disabled the ThreadSan. I have also left a comment as to how to re-enable it.

**Comment by bassoy** [comment]
> > Thanks for the info. We shall than disable the thread sanitizer for push and pull request for now.
> 
> I have disabled the ThreadSan. I have also left a comment as to how to re-enable it.

looks good.

**Comment by bassoy** [comment]
Can you inlcude a separate (visuable) workflow for the sanitizer checks?

**Comment by coder3101** [comment]
I can separately create 2-3 workflows for each sanitizer. Say "Address Sanitizer" running on gcc-8/9 and remove address sanitizer from linux_gcc.yml

This way, if some sanitizer issues occurred the builds will still pass but this sanitizer workflow will fail.

Do you want this?

I have mentioned some benefits of this approach, but there is a downside to this approach as well, we will build same code twice onces with Sanitizer and other time without sanitizer on same toolchain (gcc/clang)

The benefits is that sanitizer enabled code will run only one or two of toolchain (say GCC-9 and clang-9) instead of whole matrix as it is done now. So matrix builds will be faster.

EDIT: There is one more benefit of this approach that we can run sanitizers with -O2  and matrix build in -O0. So we will test same code on both debug and release mode!

**Comment by coder3101** [comment]
> Can you inlcude a separate (visuable) workflow for the sanitizer checks?

I have separated the Sanitizers. into 3 different Jobs, Address, Undefined, and Thread Sanitizer. Each is run on clang-9 and gcc-9 with -std=c++2a with default optimization. (except in thread sanitizer, it is run in -O2 because otherwise, it will be super slow).

The build matrices now only build the code.
 - Linux Clang builds and runs tests in full optimization (o3)
 - Linux Gcc builds and runs the tests in full un-optimization (o0)

You can check the status of each builds now!

**Comment by bassoy** [comment]
Looks very good - as we have now so many, we should organize the badges better.

My suggestion:
Let us not put the compatiable compilers in the readme.md in [properties](https://github.com/BoostGSoC20/ublas/tree/github-actions#properties). Instead, I recommend you to place the description just under the table of [build-status](https://github.com/BoostGSoC20/ublas/tree/github-actions#build-status), so that we know with which compiler is tested in Linux (Ubuntu 20.04 - build-status).

Perhaps something like this:

Build & Test

|     Operating System                | Compiler          | [master-badge]   | [develop-badge]  |
| ---------------------------------------- |:---------------------|:---------------------:| ---------------------:|
| Linux (Ubuntu 20.04 x86_64)  | gcc-{9,10}        | [passed-badge] | [passed-badge] |
| Linux (Ubuntu 20.04 x86_64)  | clang-{}                | [passed-badge] | [passed-badge] |
| Windows 10 (x86_64)             | msvc-{}                | [passed-badge] | [passed-badge] |
| Mac OS (x86_64)                   | clang-{}                 | [passed-badge] | [passed-badge] |

Additional Sanitizer Tests

|                                                  | Master Branch   | Develop Branch  |
| ---------------------------------------- |:---------------------|:---------------------:|
| Sanitizers (UB)           | [passed-badge] | [passed-badge] |
| Sanitizers (TH)           | [passed-badge] | [passed-badge] |
| Sanitizers (ADD)           | [passed-badge] | [passed-badge] |
|  Codecov                                  | [passed-badge] | [passed-badge] |
| Clang-Format          | [passed-badge] | [passed-badge] |
| Clang-Tidy           | [passed-badge] | [passed-badge] |

**Comment by coder3101** [comment]
I have updated the Readme badges in that above mentioned format.

**Comment by bassoy** [comment]
> I have updated the Readme badges in that above mentioned format.

Thanks. Final wish: could you put extra information regarding the flags in the build section: 
something like (Debug/Release) where Debug is `-g -Wall -Werror` and Release is `-O3 -Wall -Werror` or something similar.

**Comment by coder3101** [comment]
>  could you put extra information regarding the flags in the build section:


Done

**Comment by bassoy** [comment]
The badge [location](https://github.com/BoostGSoC20/ublas/workflows/Linux%20Clang%20Release/badge.svg?branch=github-actions) does not seem to work

**Comment by bassoy** [comment]
Linker Flags are not that important and I would not mention them.

**Comment by coder3101** [comment]
> 
> 
> Linker Flags are not that important and I would not mention them.

Ok Removed

**Comment by coder3101** [comment]
> 
> 
> The badge [location](https://github.com/BoostGSoC20/ublas/workflows/Linux%20Clang%20Release/badge.svg?branch=github-actions) does not seem to work

I might have missed adding that as a hyperlink. Have done it now.

**Comment by coder3101** [comment]
Shouldn't this be closed now?
