### ISSUE TITLE
Conclude the handling of Clang-Format and Clang-Tidy

### ISSUE THREAD

**Issue by bassoy** [BoostGSoC20/ublas#13]
Refering to issue https://github.com/BoostGSoC20/ublas/issues/4#issuecomment-645274452
We need to conclude whether we want to have a review script and github action, see branch https://github.com/BoostGSoC20/ublas/tree/clang-tidy-review-check

**Comment by coder3101** [comment]
The above PR introduces the clang-tidy review in action. I have written the review script (took a day) and registered it on Boost Software License 1.0. If you believe that review script is working as expected, you can close this issue!
