### ISSUE TITLE
Add cmake as build system

### ISSUE THREAD

**Issue by bassoy** [BoostGSoC20/ublas#6]
next to the boost.build, cmake should help to build Boost.uBlas tests and examples 
an example is given in https://github.com/boostorg/gil

**Comment by coder3101** [comment]
I think It will be better to work on this after CI stuff if done. When working with code, I used to CMake-ify uBLAS for better IDE support. (Many IDE don't parse B2 projects but can parse CMake Projects).

**Comment by bassoy** [comment]
Please put in future work. Let’s have the pull request for ublas as fast as possible.

**Comment by coder3101** [comment]
This cannot be deferred to `future work` because in order to develop uBLAS. I use IDE that has support for parsing and setting up the project from CMakeLists.txt

In order to develop for uBLAS. I will need a CMake file anyways, So I think it should be in next phase
